#language
language: ruby
#supported versions of ruby for test
rvm:
  - "1.9.3"

script:
  - bundle install
  #- RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
#  - bundle exec rake db:test:prepare
#  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml
  #- mysql -e 'create database projestimate_test'