language: ruby
rvm:
- 1.9.3
env:
- RAILS_ENV=test

before_script:
- cp config/database.travis.yml config/database.yml
- cp config/sensitive_settings.travis.yml config/sensitive_settings.yml
- mysql -e 'create database projestimate_test;'
- mysql -e 'create table projestimate_test.work_element_types(id INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(255), alias VARCHAR(255), description TEXT,
            project_area_id INTEGER, created_at DATETIME, updated_at DATETIME, peicon_id INTEGER, uuid VARCHAR(255), record_status_id INTEGER, custom_value VARCHAR(255),
            owner_id INTEGER, change_comment TEXT, reference_id INTEGER, reference_uuid VARCHAR(255);'

script:
#  - bundle install
#  - bundle exec rake db:schema:load
#  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN = 551f2cd12272922000636791925d42fd6a732f6e48d89ceadc5bffaf2d7c271c bundle exec rake  ###- bundle exec rspec spec

after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"

env:
  global:
  - secure: AMm3k90rvYJPtymz0bTKfuQnSDeKT99CkXSBMLpFOjPHox+VkHcmeGYGOcS7ozIkX8GuD7T218h/Z8N2fnK4IrD0jtggHWthhXUVjEON6RzmgEdfNjUXuRQU0y9jpSn5UN9JtvacyxjCtkd7fK6/u2pAVyd76LV+5NF3c2Cw2dI=
  - secure: Vq2tsRX2/JsZqeSi259tqa2wa+ldyxy0mt3c0L7TyT2TBuaAmh3WzsDQ8G9NYAHJzkQB4zkj0M+XqgZzVl3dPXLsigfyNtWukJBiH6RfWxEkGlmpNw3d+T19sHK+4JpK1XOZ6Pg9jGVDeB+Sw+sR7rE8lM01UZjtFBY6j2sVE+4=
  - secure: gWqzbPZxB1fl1DKdv4JxXSZZbfn2JzUK2zmjvW4TsfAJZ56EoA6IonVFluEtSgBd7D7VzQApWIFbh/w3rQiOst5csYnNN4qMOBPoAClOy/bm+tbOCxBgpimoJvfGP+0sKnXayO8gKSEmkYFUlgZExqdGuyuJ4D4adRpiTZ8xNdE=
  - secure: X29RR7exbZEXty5EKsMS8XZCkEA3+eswXvhDXt1cgseop+B0SL/6KNJVQJ7I1wFMZBHf5LzZdX5H/8Ub8ORXu5KF14UY5P1tEFEPJ4fjlq+eqaYMEDH8XjN+TGlxIEOO/JzdlkWS5afm1UWjVC9vYcK2VQYHhXVYd6raNONbuhE=
  - secure: YCDQFh29yi3BOFXViMQ4VoVclzvstpJxm9PbfVupbOKZhPf/b1QRZg3YkZQeD55grnPPesjG5twK407LVMcETSuYO2fxv4+XCKM44xao1iDtnJ4c2piySHWowcxozryOjRUiAy+7LTiKeUGkGMCZlHFpKP+AicKMXRNWPy5MYW0=
  - secure: VH6hoN43bDpjFy9wLZgNxHXDdxFlp6Ib3U6ABTzDhn9V4tpVKEllC69By3KSKERSqeqecytt86TFSK13LT24V07lv+LJ92llXY49Whf8/UsIhLRqLxUxoUKEsSV6s3iZxGzhhy3z9V7WpeGqiOVvHnmZu+ekk2AwPn4h1tYVo60=
  - secure: Y81x3GYwhT4V4N9CUs4VnUiLGrHVjnYnBBFQMaBumS/kZOJwc+dCZqkUmt1rhfsIKMgzlC4TLcFhxdQ540fDIVuw95m3KTilXM7CAoB7zc3kGPcoGtxQQ7M6y4wVdANYyVFTc+QpQVyllkWlFykeUsaLf9Ku7U+Xk15aIkBbAeo=
  - secure: RNVHoOGyzWUUCnbAcKD1jwSoVW+Qi5cA4I9luwFokDU7YkT0toKfhtJjcNOegbt44ctVclb64oI4gtzGwYygVklnUmif0tTyGRjwYqwvOgsnISIQJxx0bQWAX8N2kh7Pa+4+z6uNhUOc3yjA8zepeHB28nVJ7Xc5WKm0/KwM81g=

  #SECRET_TOKEN
  - secure: HV2ss8dRB0+pgg95UxUyLFnIGOuuHYRHvyx8TXjXAA3kvYsE9dbOOEU8R3Hpde7ya6ALqq2MLH15/Jg5LAIY2jZOWOsnNdSsKplKJ7nguFC30FCfKQfV6WSnq9oOJW1OCfuWSDYPJZ/Utgqe7qXEtn23CJCoLjbhxMZkvV497eo=

addons:
    code_climate:
        repo_token: 551f2cd12272922000636791925d42fd6a732f6e48d89ceadc5bffaf2d7c271c