development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_development
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: projestimate_production
  reconnect: false
  host: localhost
  username: root
  password:
  encoding: utf8
