development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_workin
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: projestimate_production
  reconnect: false
  host: localhost
  username: root
  password:
  encoding: utf8
