development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate
  pool: 5
  username: root
  password: rootspirula
  host: localhost


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_test
  pool: 5
  username: root
  password: rootspirula
  host: localhost


production:
  adapter: mysql2
  database: projestimate
  reconnect: false
  host: localhost
  username: root
  password: rootspirula
  encoding: utf8
