development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_dev_db_name
  pool: 5
  username: add_your_username
  password: changeit
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: projestimate_test_db_name
  pool: 5
  username: add_your_username
  password: changeit
  host: localhost

production:
  adapter: mysql2
  database: projestimate_prod_db_name
  reconnect: false
  host: localhost
  username: add_your_username
  password: changeit
  encoding: utf8
