development:
  adapter: mysql2
  database: projestimate_development_correction
  pool: 5
  username: root
  password: estimancy
  host: localhost

production:
  adapter: mysql2
  database: projestimate_development_correction
  pool: 5
  username: root
  password: estimancy
  host: localhost

test:
  adapter: mysql2
  database: projestimate_test
  pool: 5
  username: root
  password: estimancy
  host: localhost