# SMTP configuration
SECRET_TOKEN: bVWlQbBNW+qLrwaTwt1bQ5YoaT/OAjlvXYZWV810xQbP6R8NJ7BccaflRjQtxylcBxcgY06imzUOLR94c2hStA==
SMTP_ADDRESS: ""
SMTP_PORT: 587
SMTP_DOMAIN: ""
SMTP_USER_NAME: ""
SMTP_PASSWORD: ""
HOST_URL: ""