# Configuration file for Sidekiq.

---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 25
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]


#To run Sidekiq in production
#bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production
#-d, Daemonize process
#-L, path to writable logfile
#-C, path to YAML config file
#-e, Application environment
