require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LivrablesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Livrable. As you add validations to Livrable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LivrablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all livrables as @livrables" do
      livrable = Livrable.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:livrables)).to eq([livrable])
    end
  end

  describe "GET show" do
    it "assigns the requested livrable as @livrable" do
      livrable = Livrable.create! valid_attributes
      get :show, {:id => livrable.to_param}, valid_session
      expect(assigns(:livrable)).to eq(livrable)
    end
  end

  describe "GET new" do
    it "assigns a new livrable as @livrable" do
      get :new, {}, valid_session
      expect(assigns(:livrable)).to be_a_new(Livrable)
    end
  end

  describe "GET edit" do
    it "assigns the requested livrable as @livrable" do
      livrable = Livrable.create! valid_attributes
      get :edit, {:id => livrable.to_param}, valid_session
      expect(assigns(:livrable)).to eq(livrable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Livrable" do
        expect {
          post :create, {:livrable => valid_attributes}, valid_session
        }.to change(Livrable, :count).by(1)
      end

      it "assigns a newly created livrable as @livrable" do
        post :create, {:livrable => valid_attributes}, valid_session
        expect(assigns(:livrable)).to be_a(Livrable)
        expect(assigns(:livrable)).to be_persisted
      end

      it "redirects to the created livrable" do
        post :create, {:livrable => valid_attributes}, valid_session
        expect(response).to redirect_to(Livrable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved livrable as @livrable" do
        post :create, {:livrable => invalid_attributes}, valid_session
        expect(assigns(:livrable)).to be_a_new(Livrable)
      end

      it "re-renders the 'new' template" do
        post :create, {:livrable => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested livrable" do
        livrable = Livrable.create! valid_attributes
        put :update, {:id => livrable.to_param, :livrable => new_attributes}, valid_session
        livrable.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested livrable as @livrable" do
        livrable = Livrable.create! valid_attributes
        put :update, {:id => livrable.to_param, :livrable => valid_attributes}, valid_session
        expect(assigns(:livrable)).to eq(livrable)
      end

      it "redirects to the livrable" do
        livrable = Livrable.create! valid_attributes
        put :update, {:id => livrable.to_param, :livrable => valid_attributes}, valid_session
        expect(response).to redirect_to(livrable)
      end
    end

    describe "with invalid params" do
      it "assigns the livrable as @livrable" do
        livrable = Livrable.create! valid_attributes
        put :update, {:id => livrable.to_param, :livrable => invalid_attributes}, valid_session
        expect(assigns(:livrable)).to eq(livrable)
      end

      it "re-renders the 'edit' template" do
        livrable = Livrable.create! valid_attributes
        put :update, {:id => livrable.to_param, :livrable => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested livrable" do
      livrable = Livrable.create! valid_attributes
      expect {
        delete :destroy, {:id => livrable.to_param}, valid_session
      }.to change(Livrable, :count).by(-1)
    end

    it "redirects to the livrables list" do
      livrable = Livrable.create! valid_attributes
      delete :destroy, {:id => livrable.to_param}, valid_session
      expect(response).to redirect_to(livrables_url)
    end
  end

end
